### ISSUE TITLE
FHIR Valueset URLs

### ISSUE THREAD

**Issue by p9g** [cqframework/cqf-measures#18]
In CQL examples, lines of CQL like
`valueset "Encounter Inpatient": 'urn:oid:2.16.840.1.113883.3.666.5.307'`
should become
`valueset "Encounter Inpatient": 'https://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113883.3.666.5.307/$expand'`

**Comment by brynrhodes** [comment]
Fixed in all examples.

**Comment by brynrhodes** [comment]
Whoops, meant to just comment that this was fixed.

**Comment by p9g** [comment]
Thanks for updating.  I'll close this, but open another issue to add some text somewhere explaining that CQL does not prescribe any details about the identifier, but implementation/execution environments may expect a URL (with or without `/$expand`) or an OID (with or without `urn:oid:`)
